version: "3.4"
services:
  jackett:
    restart: unless-stopped
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONO_TLS_PROVIDER=btls
      - AUTO_UPDATE=true
    volumes:
      - ${DVOL}/downloads:/downloads
      - ${CVOL}/jackett:/config
    ports:
      - 9117:9117

  sonarr:
    restart: unless-stopped
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${DVOL}/tv:/tv
      - ${DVOL}/downloads:/downloads
      - ${CVOL}/sonarr:/config
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONO_TLS_PROVIDER=btls

  radarr:
    restart: unless-stopped
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ${DVOL}/movies:/movies
      - ${DVOL}/downloads:/downloads
      - ${CVOL}/radarr:/config
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sabnzbd:
    restart: unless-stopped
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - ${DVOL}/incomplete:/incomplete-downloads
      - ${DVOL}/downloads:/downloads
      - ${CVOL}/sabnzbd:/config
    ports:
      - 8080:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  transmission:
    restart: unless-stopped
    image: linuxserver/transmission
    container_name: transmission
    volumes:
      - ${SABVOL}/incomplete:/incomplete-downloads
      - ${DVOL}/downloads:/downloads
      - ${CVOL}/transmission:/config
      - ${DVOL}/watch:/watch
    ports:
      - "51413:51413"
      - "51413:51413/udp"
      - 9091:9091

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - ${CVOL}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9000:9000

  plex:
    restart: unless-stopped
    image: linuxserver/plex:latest
    container_name: plex
    volumes:
      - ${DVOL}/movies:/data/movies
      - ${DVOL}/tv:/data/tv
      - ${DVOL}/downloads:/downloads
      - ${CVOL}/plex:/config
      - ${DVOL}/photos:/data/photos
      - /dev/shm:/transcode
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=latest

  adguard:
    restart: unless-stopped
    container_name: adguard
    image: adguard/adguardhome
    volumes:
      - ${CVOL}/adguard/workdir:/opt/adguardhome/work
      - ${CVOL}/adguard/confdir:/opt/adguardhome/conf
    ports:
      - 53:53
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 8084:80
      - 8484:443
      - 443:443/udp
      - 3000:3000
      - 853:853
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443
      - 5443:5443/udp

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ${CVOL}/readarr/data:/config
      - ${DVOL}/books:/books
      - ${DVOL}/audiobooks:/audiobooks
      - ${DVOL}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  overseerr:
    restart: unless-stopped
    image: linuxserver/overseerr
    container_name: overseerr
    volumes:
      - ${CVOL}/overseerr:/config
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.5.0.1/24
          gateway: 172.5.0.1
